<?php

namespace AppBundle\Repository;

/**
 * EmotionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmotionsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $sessionId
     * @return array
     */
    public function getAllEmotions($sessionId) : array
    {
        $query = "SELECT AVG(E.anger) AS anger, AVG(E.contempt) AS contempt, AVG(E.disgust) AS disgust, 
                AVG(E.fear) AS fear, AVG(E.happiness) AS happiness, AVG(E.neutral) AS neutral, AVG(E.sadness) AS sadness, AVG(E.surprise) AS surprise,
                DATE_FORMAT(E.datetime, '%Y-%m-%d %H:%i') as datetime
            FROM emotions AS E
            WHERE E.session_id = '$sessionId'
            GROUP BY DATE_FORMAT(E.datetime, '%Y-%m-%d %H:%i')";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($query);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
